
package top.zzh.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://server.zzh.top/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.zzh.top/", className = "top.zzh.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.zzh.top/", className = "top.zzh.client.SayHelloResponse")
    @Action(input = "http://server.zzh.top/HelloServiceImpl/sayHelloRequest", output = "http://server.zzh.top/HelloServiceImpl/sayHelloResponse")
    public void sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://server.zzh.top/", className = "top.zzh.client.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.zzh.top/", className = "top.zzh.client.SayResponse")
    @Action(input = "http://server.zzh.top/HelloServiceImpl/sayRequest", output = "http://server.zzh.top/HelloServiceImpl/sayResponse")
    public String say(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
